Bank account verification integration
hmrc/vat-deferral-new-payment-scheme-frontend pull request #5
Opened 2020-12-03 15:41 UTC by PaulThor

2020-12-03 17:31 UTC, hmrclt requested changes

2020-12-03 17:31 UTC, hmrclt commented on app/uk/gov/hmrc/vatdeferralnewpaymentschemefrontend/connectors/BavfConnector.scala
> +    import InitRequest.writes
personally I'd put these imports at the top of the file with the others.

2020-12-03 17:31 UTC, hmrclt commented on app/uk/gov/hmrc/vatdeferralnewpaymentschemefrontend/controllers/MonthsController.scala
> +
You could do - 
```
    Future.successful(
      journeySession.outStandingAmount match {
        case Some(outStandingAmount) => Ok(howManyMonthsPage(getMonths(outStandingAmount)))
        case _ => Redirect(routes.DeferredVatBillController.get())
      }
    )
```

2020-12-03 17:31 UTC, hmrclt commented on app/uk/gov/hmrc/vatdeferralnewpaymentschemefrontend/controllers/MonthsController.scala
> +      val months = request.body.asFormUrlEncoded.map(a => a.mapValues(_.last)).flatMap(b => b.get("how-many-months"))
```
request.body.asFormUrlEncoded.flatMap(_.mapValues(_.last).get("how-many-months"))
```

2020-12-03 17:31 UTC, hmrclt commented on app/uk/gov/hmrc/vatdeferralnewpaymentschemefrontend/controllers/MonthsController.scala
> +
You may also want to consider writing the auth logic using an ActionBuilder. That way you would have a synchronous and asynchronous method to call on.

2020-12-03 17:31 UTC, hmrclt commented on app/uk/gov/hmrc/vatdeferralnewpaymentschemefrontend/controllers/WhenToPayController.scala
> +  }
As above, you can move the Future.successful to the outside, but I suspect the ideal approach would be to use an actionbuilder here.

2020-12-03 17:31 UTC, hmrclt commented on app/uk/gov/hmrc/vatdeferralnewpaymentschemefrontend/model/Bavf/Enumerable.scala
> +object Enumerable {
You could consider the enumeratum library here.

2020-12-03 17:31 UTC, hmrclt commented on app/uk/gov/hmrc/vatdeferralnewpaymentschemefrontend/model/Bavf/InitRequestAddress.scala
> +case class InitRequestAddress(lines: List[String], town: Option[String], postcode: Option[String])
Is this not the same thing as CompleteResponseAddress?

2020-12-03 17:31 UTC, hmrclt commented on app/uk/gov/hmrc/vatdeferralnewpaymentschemefrontend/views/WhenToPayPage.scala.html
> +            <form action="" method="POST">
is the action intentionally blank here?

2020-12-04 09:56 UTC, PaulThor commented on app/uk/gov/hmrc/vatdeferralnewpaymentschemefrontend/controllers/WhenToPayController.scala
> +  }
Might need to look into action builders, but will leave it for now

2020-12-04 09:57 UTC, PaulThor commented on app/uk/gov/hmrc/vatdeferralnewpaymentschemefrontend/model/Bavf/Enumerable.scala
> +object Enumerable {
Ok - need to have a look into that, I took this code from the bank-account-verification-frontend-example project so I will look at improving it at a later date

2020-12-04 09:58 UTC, PaulThor commented on app/uk/gov/hmrc/vatdeferralnewpaymentschemefrontend/model/Bavf/InitRequestAddress.scala
> +case class InitRequestAddress(lines: List[String], town: Option[String], postcode: Option[String])
I took this code from bank-account-verification-example-frontend so I'll look into at a later date

2020-12-04 14:47 UTC, merged